stages:
  - test
  - build
job:
  #stages定义阶段
  stage: test
  tags:
    - java2004
  script:
    - eoch hello world #测试回声效果，执行效果
job1:
    stage: build
    tags:
      - ssm
    script:
      - eoch hello gitlab
