stages:
  - test
  - build
#定义任务标识
job:
  #stages定义阶段
  stage: test
  script:
    - echo hello world #测试回声效果，执行效果
    - /usr/local/maven/apache-maven-3.6.3/bin/mvn -DskipTests=true package #定义maven打包当前项目文件
job1:
    stage: build
    script:
      - echo hello gitlab
