# docker-compose.yml
version: "3.1"
services:
  testci:
    build: compose # 加载Dockerfile自定义镜像文件
    restart: always # docker重新启动时启动
    image: ssm:1.0 # 自定义镜像名称:tag标识
    container_name: tomcat200
    ports:
      - 8089:8080